// Code generated by protoc-gen-go. DO NOT EDIT.
// source: query.proto

package query

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Date                 int32    `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"`
	Status               int32    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	HotelId              string   `protobuf:"bytes,4,opt,name=hotelId,proto3" json:"hotelId,omitempty"`
	Adviser              string   `protobuf:"bytes,5,opt,name=Adviser,proto3" json:"Adviser,omitempty"`
	HrId                 string   `protobuf:"bytes,6,opt,name=hrId,proto3" json:"hrId,omitempty"`
	PtId                 string   `protobuf:"bytes,7,opt,name=ptId,proto3" json:"ptId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{0}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *QueryRequest) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *QueryRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *QueryRequest) GetHotelId() string {
	if m != nil {
		return m.HotelId
	}
	return ""
}

func (m *QueryRequest) GetAdviser() string {
	if m != nil {
		return m.Adviser
	}
	return ""
}

func (m *QueryRequest) GetHrId() string {
	if m != nil {
		return m.HrId
	}
	return ""
}

func (m *QueryRequest) GetPtId() string {
	if m != nil {
		return m.PtId
	}
	return ""
}

type QueryReply struct {
	OrderOrigins         string   `protobuf:"bytes,1,opt,name=orderOrigins,proto3" json:"orderOrigins,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReply) Reset()         { *m = QueryReply{} }
func (m *QueryReply) String() string { return proto.CompactTextString(m) }
func (*QueryReply) ProtoMessage()    {}
func (*QueryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{1}
}

func (m *QueryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReply.Unmarshal(m, b)
}
func (m *QueryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReply.Marshal(b, m, deterministic)
}
func (m *QueryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReply.Merge(m, src)
}
func (m *QueryReply) XXX_Size() int {
	return xxx_messageInfo_QueryReply.Size(m)
}
func (m *QueryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReply proto.InternalMessageInfo

func (m *QueryReply) GetOrderOrigins() string {
	if m != nil {
		return m.OrderOrigins
	}
	return ""
}

type QueryPTRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	PtId                 string   `protobuf:"bytes,2,opt,name=ptId,proto3" json:"ptId,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	InviterId            string   `protobuf:"bytes,4,opt,name=inviterId,proto3" json:"inviterId,omitempty"`
	PtStatus             int32    `protobuf:"varint,5,opt,name=ptStatus,proto3" json:"ptStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryPTRequest) Reset()         { *m = QueryPTRequest{} }
func (m *QueryPTRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPTRequest) ProtoMessage()    {}
func (*QueryPTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{2}
}

func (m *QueryPTRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPTRequest.Unmarshal(m, b)
}
func (m *QueryPTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPTRequest.Marshal(b, m, deterministic)
}
func (m *QueryPTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPTRequest.Merge(m, src)
}
func (m *QueryPTRequest) XXX_Size() int {
	return xxx_messageInfo_QueryPTRequest.Size(m)
}
func (m *QueryPTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPTRequest proto.InternalMessageInfo

func (m *QueryPTRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *QueryPTRequest) GetPtId() string {
	if m != nil {
		return m.PtId
	}
	return ""
}

func (m *QueryPTRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *QueryPTRequest) GetInviterId() string {
	if m != nil {
		return m.InviterId
	}
	return ""
}

func (m *QueryPTRequest) GetPtStatus() int32 {
	if m != nil {
		return m.PtStatus
	}
	return 0
}

type PT struct {
	PtId                 string   `protobuf:"bytes,1,opt,name=ptId,proto3" json:"ptId,omitempty"`
	AdviserId            string   `protobuf:"bytes,2,opt,name=adviserId,proto3" json:"adviserId,omitempty"`
	AgentId              string   `protobuf:"bytes,3,opt,name=agentId,proto3" json:"agentId,omitempty"`
	ApplyTime            int32    `protobuf:"varint,4,opt,name=applyTime,proto3" json:"applyTime,omitempty"`
	SignTime             int32    `protobuf:"varint,5,opt,name=signTime,proto3" json:"signTime,omitempty"`
	OrderId              string   `protobuf:"bytes,6,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Id                   string   `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	PtStatus             int32    `protobuf:"varint,8,opt,name=ptStatus,proto3" json:"ptStatus,omitempty"`
	Type                 int32    `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	InviterId            string   `protobuf:"bytes,10,opt,name=inviterId,proto3" json:"inviterId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PT) Reset()         { *m = PT{} }
func (m *PT) String() string { return proto.CompactTextString(m) }
func (*PT) ProtoMessage()    {}
func (*PT) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{3}
}

func (m *PT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PT.Unmarshal(m, b)
}
func (m *PT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PT.Marshal(b, m, deterministic)
}
func (m *PT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PT.Merge(m, src)
}
func (m *PT) XXX_Size() int {
	return xxx_messageInfo_PT.Size(m)
}
func (m *PT) XXX_DiscardUnknown() {
	xxx_messageInfo_PT.DiscardUnknown(m)
}

var xxx_messageInfo_PT proto.InternalMessageInfo

func (m *PT) GetPtId() string {
	if m != nil {
		return m.PtId
	}
	return ""
}

func (m *PT) GetAdviserId() string {
	if m != nil {
		return m.AdviserId
	}
	return ""
}

func (m *PT) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *PT) GetApplyTime() int32 {
	if m != nil {
		return m.ApplyTime
	}
	return 0
}

func (m *PT) GetSignTime() int32 {
	if m != nil {
		return m.SignTime
	}
	return 0
}

func (m *PT) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *PT) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PT) GetPtStatus() int32 {
	if m != nil {
		return m.PtStatus
	}
	return 0
}

func (m *PT) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PT) GetInviterId() string {
	if m != nil {
		return m.InviterId
	}
	return ""
}

type QueryPTReply struct {
	OrderPts             []*PT    `protobuf:"bytes,1,rep,name=orderPts,proto3" json:"orderPts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryPTReply) Reset()         { *m = QueryPTReply{} }
func (m *QueryPTReply) String() string { return proto.CompactTextString(m) }
func (*QueryPTReply) ProtoMessage()    {}
func (*QueryPTReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{4}
}

func (m *QueryPTReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPTReply.Unmarshal(m, b)
}
func (m *QueryPTReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPTReply.Marshal(b, m, deterministic)
}
func (m *QueryPTReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPTReply.Merge(m, src)
}
func (m *QueryPTReply) XXX_Size() int {
	return xxx_messageInfo_QueryPTReply.Size(m)
}
func (m *QueryPTReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPTReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPTReply proto.InternalMessageInfo

func (m *QueryPTReply) GetOrderPts() []*PT {
	if m != nil {
		return m.OrderPts
	}
	return nil
}

type QueryRemarkRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	PtId                 string   `protobuf:"bytes,2,opt,name=ptId,proto3" json:"ptId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRemarkRequest) Reset()         { *m = QueryRemarkRequest{} }
func (m *QueryRemarkRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRemarkRequest) ProtoMessage()    {}
func (*QueryRemarkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{5}
}

func (m *QueryRemarkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRemarkRequest.Unmarshal(m, b)
}
func (m *QueryRemarkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRemarkRequest.Marshal(b, m, deterministic)
}
func (m *QueryRemarkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRemarkRequest.Merge(m, src)
}
func (m *QueryRemarkRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRemarkRequest.Size(m)
}
func (m *QueryRemarkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRemarkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRemarkRequest proto.InternalMessageInfo

func (m *QueryRemarkRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *QueryRemarkRequest) GetPtId() string {
	if m != nil {
		return m.PtId
	}
	return ""
}

type QueryRemarkReply struct {
	Remark               string   `protobuf:"bytes,1,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRemarkReply) Reset()         { *m = QueryRemarkReply{} }
func (m *QueryRemarkReply) String() string { return proto.CompactTextString(m) }
func (*QueryRemarkReply) ProtoMessage()    {}
func (*QueryRemarkReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{6}
}

func (m *QueryRemarkReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRemarkReply.Unmarshal(m, b)
}
func (m *QueryRemarkReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRemarkReply.Marshal(b, m, deterministic)
}
func (m *QueryRemarkReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRemarkReply.Merge(m, src)
}
func (m *QueryRemarkReply) XXX_Size() int {
	return xxx_messageInfo_QueryRemarkReply.Size(m)
}
func (m *QueryRemarkReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRemarkReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRemarkReply proto.InternalMessageInfo

func (m *QueryRemarkReply) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type QueryExperienceRequest struct {
	PtId                 string   `protobuf:"bytes,1,opt,name=ptId,proto3" json:"ptId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryExperienceRequest) Reset()         { *m = QueryExperienceRequest{} }
func (m *QueryExperienceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryExperienceRequest) ProtoMessage()    {}
func (*QueryExperienceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{7}
}

func (m *QueryExperienceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryExperienceRequest.Unmarshal(m, b)
}
func (m *QueryExperienceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryExperienceRequest.Marshal(b, m, deterministic)
}
func (m *QueryExperienceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryExperienceRequest.Merge(m, src)
}
func (m *QueryExperienceRequest) XXX_Size() int {
	return xxx_messageInfo_QueryExperienceRequest.Size(m)
}
func (m *QueryExperienceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryExperienceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryExperienceRequest proto.InternalMessageInfo

func (m *QueryExperienceRequest) GetPtId() string {
	if m != nil {
		return m.PtId
	}
	return ""
}

type QueryExperienceReply struct {
	WorkExperience       string   `protobuf:"bytes,1,opt,name=workExperience,proto3" json:"workExperience,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryExperienceReply) Reset()         { *m = QueryExperienceReply{} }
func (m *QueryExperienceReply) String() string { return proto.CompactTextString(m) }
func (*QueryExperienceReply) ProtoMessage()    {}
func (*QueryExperienceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{8}
}

func (m *QueryExperienceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryExperienceReply.Unmarshal(m, b)
}
func (m *QueryExperienceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryExperienceReply.Marshal(b, m, deterministic)
}
func (m *QueryExperienceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryExperienceReply.Merge(m, src)
}
func (m *QueryExperienceReply) XXX_Size() int {
	return xxx_messageInfo_QueryExperienceReply.Size(m)
}
func (m *QueryExperienceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryExperienceReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryExperienceReply proto.InternalMessageInfo

func (m *QueryExperienceReply) GetWorkExperience() string {
	if m != nil {
		return m.WorkExperience
	}
	return ""
}

type QueryAgentRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAgentRequest) Reset()         { *m = QueryAgentRequest{} }
func (m *QueryAgentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAgentRequest) ProtoMessage()    {}
func (*QueryAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{9}
}

func (m *QueryAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAgentRequest.Unmarshal(m, b)
}
func (m *QueryAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAgentRequest.Marshal(b, m, deterministic)
}
func (m *QueryAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAgentRequest.Merge(m, src)
}
func (m *QueryAgentRequest) XXX_Size() int {
	return xxx_messageInfo_QueryAgentRequest.Size(m)
}
func (m *QueryAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAgentRequest proto.InternalMessageInfo

func (m *QueryAgentRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type QueryAgentReply struct {
	AgentList            string   `protobuf:"bytes,1,opt,name=agentList,proto3" json:"agentList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAgentReply) Reset()         { *m = QueryAgentReply{} }
func (m *QueryAgentReply) String() string { return proto.CompactTextString(m) }
func (*QueryAgentReply) ProtoMessage()    {}
func (*QueryAgentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{10}
}

func (m *QueryAgentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAgentReply.Unmarshal(m, b)
}
func (m *QueryAgentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAgentReply.Marshal(b, m, deterministic)
}
func (m *QueryAgentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAgentReply.Merge(m, src)
}
func (m *QueryAgentReply) XXX_Size() int {
	return xxx_messageInfo_QueryAgentReply.Size(m)
}
func (m *QueryAgentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAgentReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAgentReply proto.InternalMessageInfo

func (m *QueryAgentReply) GetAgentList() string {
	if m != nil {
		return m.AgentList
	}
	return ""
}

type QueryOOARequest struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOOARequest) Reset()         { *m = QueryOOARequest{} }
func (m *QueryOOARequest) String() string { return proto.CompactTextString(m) }
func (*QueryOOARequest) ProtoMessage()    {}
func (*QueryOOARequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{11}
}

func (m *QueryOOARequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOOARequest.Unmarshal(m, b)
}
func (m *QueryOOARequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOOARequest.Marshal(b, m, deterministic)
}
func (m *QueryOOARequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOOARequest.Merge(m, src)
}
func (m *QueryOOARequest) XXX_Size() int {
	return xxx_messageInfo_QueryOOARequest.Size(m)
}
func (m *QueryOOARequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOOARequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOOARequest proto.InternalMessageInfo

func (m *QueryOOARequest) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *QueryOOARequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type QueryOOAReply struct {
	OrderList            []string `protobuf:"bytes,1,rep,name=order_list,json=orderList,proto3" json:"order_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOOAReply) Reset()         { *m = QueryOOAReply{} }
func (m *QueryOOAReply) String() string { return proto.CompactTextString(m) }
func (*QueryOOAReply) ProtoMessage()    {}
func (*QueryOOAReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{12}
}

func (m *QueryOOAReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOOAReply.Unmarshal(m, b)
}
func (m *QueryOOAReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOOAReply.Marshal(b, m, deterministic)
}
func (m *QueryOOAReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOOAReply.Merge(m, src)
}
func (m *QueryOOAReply) XXX_Size() int {
	return xxx_messageInfo_QueryOOAReply.Size(m)
}
func (m *QueryOOAReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOOAReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOOAReply proto.InternalMessageInfo

func (m *QueryOOAReply) GetOrderList() []string {
	if m != nil {
		return m.OrderList
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryRequest)(nil), "QueryRequest")
	proto.RegisterType((*QueryReply)(nil), "QueryReply")
	proto.RegisterType((*QueryPTRequest)(nil), "QueryPTRequest")
	proto.RegisterType((*PT)(nil), "PT")
	proto.RegisterType((*QueryPTReply)(nil), "QueryPTReply")
	proto.RegisterType((*QueryRemarkRequest)(nil), "QueryRemarkRequest")
	proto.RegisterType((*QueryRemarkReply)(nil), "QueryRemarkReply")
	proto.RegisterType((*QueryExperienceRequest)(nil), "QueryExperienceRequest")
	proto.RegisterType((*QueryExperienceReply)(nil), "QueryExperienceReply")
	proto.RegisterType((*QueryAgentRequest)(nil), "QueryAgentRequest")
	proto.RegisterType((*QueryAgentReply)(nil), "QueryAgentReply")
	proto.RegisterType((*QueryOOARequest)(nil), "QueryOOARequest")
	proto.RegisterType((*QueryOOAReply)(nil), "QueryOOAReply")
}

func init() { proto.RegisterFile("query.proto", fileDescriptor_5c6ac9b241082464) }

var fileDescriptor_5c6ac9b241082464 = []byte{
	// 592 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x9d, 0x26, 0x4d, 0x26, 0x4d, 0xda, 0x2c, 0x10, 0x2c, 0xab, 0x88, 0x6a, 0x0f, 0x28,
	0xaa, 0x60, 0x8b, 0xc2, 0x81, 0x03, 0x12, 0x52, 0x40, 0x1c, 0x22, 0x21, 0x39, 0x84, 0xdc, 0x51,
	0xc0, 0xdb, 0x74, 0xd5, 0x34, 0x71, 0xed, 0x4d, 0x21, 0x57, 0xce, 0x7c, 0x0c, 0x9f, 0xc4, 0xa7,
	0xa0, 0x19, 0xaf, 0xbd, 0x76, 0x12, 0x04, 0xe2, 0xe6, 0x79, 0xbb, 0x33, 0xef, 0xed, 0xbc, 0x19,
	0x43, 0xeb, 0x76, 0x2d, 0xe3, 0x8d, 0x88, 0xe2, 0x95, 0x5e, 0xf1, 0x9f, 0x0e, 0x1c, 0x7d, 0xc0,
	0x78, 0x22, 0x6f, 0xd7, 0x32, 0xd1, 0xcc, 0x83, 0xc3, 0x55, 0x1c, 0xca, 0x78, 0x14, 0x7a, 0xce,
	0x99, 0xd3, 0x6f, 0x4e, 0xb2, 0x90, 0x31, 0x38, 0x08, 0x67, 0x5a, 0x7a, 0xee, 0x99, 0xd3, 0xaf,
	0x4d, 0xe8, 0x9b, 0xf5, 0xa0, 0x9e, 0xe8, 0x99, 0x5e, 0x27, 0x5e, 0x95, 0x50, 0x13, 0x61, 0x95,
	0xab, 0x95, 0x96, 0x8b, 0x51, 0xe8, 0x1d, 0xa4, 0x55, 0x4c, 0x88, 0x27, 0xc3, 0xf0, 0x4e, 0x25,
	0x32, 0xf6, 0x6a, 0xe9, 0x89, 0x09, 0xb1, 0xfe, 0x15, 0xd2, 0xd6, 0x09, 0xa6, 0x6f, 0xc4, 0x22,
	0x3d, 0x0a, 0xbd, 0xc3, 0x14, 0xc3, 0x6f, 0xfe, 0x1c, 0xc0, 0x28, 0x8e, 0x16, 0x1b, 0xc6, 0xe1,
	0x88, 0x04, 0x06, 0xb1, 0x9a, 0xab, 0x65, 0x62, 0x44, 0x97, 0x30, 0xfe, 0xc3, 0x81, 0x0e, 0xa5,
	0x8c, 0xa7, 0xff, 0xf4, 0x4c, 0xa2, 0x74, 0x2d, 0x25, 0x62, 0x7a, 0x13, 0x49, 0xf3, 0x48, 0xfa,
	0x66, 0xa7, 0xd0, 0x54, 0xcb, 0x3b, 0xa5, 0xa9, 0x46, 0xfa, 0x48, 0x0b, 0x30, 0x1f, 0x1a, 0x91,
	0xfe, 0x98, 0xb6, 0xa6, 0x46, 0x59, 0x79, 0xcc, 0xbf, 0xbb, 0xe0, 0x8e, 0xa7, 0x39, 0x91, 0x53,
	0x20, 0x3a, 0x85, 0xe6, 0x2c, 0x6d, 0x47, 0xae, 0xc0, 0x02, 0x28, 0x7a, 0x36, 0x97, 0x4b, 0x4c,
	0xaa, 0xa6, 0xa2, 0x4d, 0x48, 0x79, 0x51, 0xb4, 0xd8, 0x4c, 0xd5, 0x8d, 0x24, 0x31, 0xb5, 0x89,
	0x05, 0x50, 0x4c, 0xa2, 0xe6, 0x4b, 0x3a, 0x34, 0x62, 0xb2, 0xb8, 0xd8, 0x88, 0x7a, 0xb9, 0x11,
	0x1d, 0x70, 0x55, 0xd6, 0x79, 0x57, 0x95, 0x9f, 0xd4, 0x28, 0x3f, 0x29, 0x6f, 0x50, 0xf3, 0x4f,
	0x0d, 0x82, 0xad, 0x06, 0xf1, 0x0b, 0x33, 0x77, 0x68, 0x09, 0xfa, 0xf8, 0x18, 0x1a, 0x44, 0x3c,
	0xd6, 0xe8, 0x61, 0xb5, 0xdf, 0x1a, 0x54, 0xc5, 0x78, 0x3a, 0xc9, 0x41, 0xfe, 0x06, 0x98, 0xb1,
	0xfd, 0x66, 0x16, 0x5f, 0xff, 0x97, 0x8f, 0xfc, 0x1c, 0x4e, 0x4a, 0x35, 0x90, 0xb8, 0x07, 0xf5,
	0x98, 0x42, 0x53, 0xc0, 0x44, 0xfc, 0x29, 0xf4, 0xe8, 0xee, 0xbb, 0x6f, 0x91, 0x8c, 0x95, 0x5c,
	0x7e, 0x91, 0x19, 0xe7, 0x1e, 0xe3, 0xf8, 0x6b, 0xb8, 0xbf, 0x73, 0x1b, 0xab, 0x3f, 0x81, 0xce,
	0xd7, 0x55, 0x7c, 0x6d, 0x61, 0x93, 0xb5, 0x85, 0xf2, 0x67, 0xd0, 0xa5, 0xfc, 0x21, 0x1a, 0xfa,
	0xd7, 0xc7, 0xf1, 0x0b, 0x38, 0x2e, 0x5e, 0x47, 0x26, 0x1c, 0x01, 0x8c, 0xde, 0xab, 0x44, 0x9b,
	0xeb, 0x16, 0xe0, 0x6f, 0x4d, 0x42, 0x10, 0x0c, 0x0b, 0xd5, 0xb3, 0x69, 0x72, 0xca, 0xd3, 0x64,
	0xb7, 0xda, 0x2d, 0x6e, 0x35, 0x17, 0xd0, 0xb6, 0x45, 0x90, 0xf3, 0x11, 0x00, 0x29, 0xfa, 0xb4,
	0x48, 0x49, 0xab, 0x48, 0x4a, 0x08, 0x92, 0x0e, 0x7e, 0xb9, 0x66, 0x55, 0x03, 0x84, 0xd8, 0x79,
	0x29, 0x6a, 0x8b, 0xe2, 0x7f, 0xc7, 0x6f, 0x09, 0xbb, 0xd4, 0xbc, 0xc2, 0x06, 0xf9, 0xc6, 0x06,
	0x97, 0xe9, 0xfd, 0x63, 0x51, 0x5e, 0x61, 0xbf, 0x2d, 0x8a, 0x03, 0xc4, 0x2b, 0xec, 0x25, 0xb4,
	0x0a, 0xee, 0xb2, 0x7b, 0x62, 0x77, 0x5e, 0xfc, 0xae, 0xd8, 0x1e, 0x00, 0x5e, 0x61, 0x59, 0x73,
	0xac, 0x1f, 0xec, 0xa1, 0xd8, 0x6f, 0xbe, 0xff, 0x40, 0xec, 0xf3, 0x99, 0x57, 0xd8, 0xab, 0xa2,
	0x83, 0x99, 0x68, 0x26, 0x76, 0x5c, 0xf5, 0x4f, 0xc4, 0x96, 0x75, 0x24, 0xbd, 0x6b, 0x5b, 0x13,
	0x5c, 0xd2, 0x19, 0x33, 0x17, 0xad, 0x65, 0x7e, 0x47, 0x94, 0xfa, 0xcf, 0x2b, 0x9f, 0xeb, 0xf4,
	0x1b, 0x7f, 0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x35, 0x7f, 0x37, 0x68, 0xd5, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryOrderClient is the client API for QueryOrder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryOrderClient interface {
	// hotel/adviser/pt query order
	QueryOrder(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryReply, error)
	// hotel/adviser query order's pt
	QueryPTOfOrder(ctx context.Context, in *QueryPTRequest, opts ...grpc.CallOption) (*QueryPTReply, error)
	// adviser query pt's remark
	QueryRemark(ctx context.Context, in *QueryRemarkRequest, opts ...grpc.CallOption) (*QueryRemarkReply, error)
	// adviser query pt' work experience
	QueryExperience(ctx context.Context, in *QueryExperienceRequest, opts ...grpc.CallOption) (*QueryExperienceReply, error)
	// adviser query agent list of order
	QueryAgentOfOrder(ctx context.Context, in *QueryAgentRequest, opts ...grpc.CallOption) (*QueryAgentReply, error)
	// agent query order
	QueryOrderOfAgent(ctx context.Context, in *QueryOOARequest, opts ...grpc.CallOption) (*QueryOOAReply, error)
}

type queryOrderClient struct {
	cc *grpc.ClientConn
}

func NewQueryOrderClient(cc *grpc.ClientConn) QueryOrderClient {
	return &queryOrderClient{cc}
}

func (c *queryOrderClient) QueryOrder(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryReply, error) {
	out := new(QueryReply)
	err := c.cc.Invoke(ctx, "/QueryOrder/QueryOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryOrderClient) QueryPTOfOrder(ctx context.Context, in *QueryPTRequest, opts ...grpc.CallOption) (*QueryPTReply, error) {
	out := new(QueryPTReply)
	err := c.cc.Invoke(ctx, "/QueryOrder/QueryPTOfOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryOrderClient) QueryRemark(ctx context.Context, in *QueryRemarkRequest, opts ...grpc.CallOption) (*QueryRemarkReply, error) {
	out := new(QueryRemarkReply)
	err := c.cc.Invoke(ctx, "/QueryOrder/QueryRemark", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryOrderClient) QueryExperience(ctx context.Context, in *QueryExperienceRequest, opts ...grpc.CallOption) (*QueryExperienceReply, error) {
	out := new(QueryExperienceReply)
	err := c.cc.Invoke(ctx, "/QueryOrder/QueryExperience", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryOrderClient) QueryAgentOfOrder(ctx context.Context, in *QueryAgentRequest, opts ...grpc.CallOption) (*QueryAgentReply, error) {
	out := new(QueryAgentReply)
	err := c.cc.Invoke(ctx, "/QueryOrder/QueryAgentOfOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryOrderClient) QueryOrderOfAgent(ctx context.Context, in *QueryOOARequest, opts ...grpc.CallOption) (*QueryOOAReply, error) {
	out := new(QueryOOAReply)
	err := c.cc.Invoke(ctx, "/QueryOrder/QueryOrderOfAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryOrderServer is the server API for QueryOrder service.
type QueryOrderServer interface {
	// hotel/adviser/pt query order
	QueryOrder(context.Context, *QueryRequest) (*QueryReply, error)
	// hotel/adviser query order's pt
	QueryPTOfOrder(context.Context, *QueryPTRequest) (*QueryPTReply, error)
	// adviser query pt's remark
	QueryRemark(context.Context, *QueryRemarkRequest) (*QueryRemarkReply, error)
	// adviser query pt' work experience
	QueryExperience(context.Context, *QueryExperienceRequest) (*QueryExperienceReply, error)
	// adviser query agent list of order
	QueryAgentOfOrder(context.Context, *QueryAgentRequest) (*QueryAgentReply, error)
	// agent query order
	QueryOrderOfAgent(context.Context, *QueryOOARequest) (*QueryOOAReply, error)
}

// UnimplementedQueryOrderServer can be embedded to have forward compatible implementations.
type UnimplementedQueryOrderServer struct {
}

func (*UnimplementedQueryOrderServer) QueryOrder(ctx context.Context, req *QueryRequest) (*QueryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOrder not implemented")
}
func (*UnimplementedQueryOrderServer) QueryPTOfOrder(ctx context.Context, req *QueryPTRequest) (*QueryPTReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryPTOfOrder not implemented")
}
func (*UnimplementedQueryOrderServer) QueryRemark(ctx context.Context, req *QueryRemarkRequest) (*QueryRemarkReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRemark not implemented")
}
func (*UnimplementedQueryOrderServer) QueryExperience(ctx context.Context, req *QueryExperienceRequest) (*QueryExperienceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryExperience not implemented")
}
func (*UnimplementedQueryOrderServer) QueryAgentOfOrder(ctx context.Context, req *QueryAgentRequest) (*QueryAgentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAgentOfOrder not implemented")
}
func (*UnimplementedQueryOrderServer) QueryOrderOfAgent(ctx context.Context, req *QueryOOARequest) (*QueryOOAReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOrderOfAgent not implemented")
}

func RegisterQueryOrderServer(s *grpc.Server, srv QueryOrderServer) {
	s.RegisterService(&_QueryOrder_serviceDesc, srv)
}

func _QueryOrder_QueryOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryOrderServer).QueryOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QueryOrder/QueryOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryOrderServer).QueryOrder(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryOrder_QueryPTOfOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryOrderServer).QueryPTOfOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QueryOrder/QueryPTOfOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryOrderServer).QueryPTOfOrder(ctx, req.(*QueryPTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryOrder_QueryRemark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRemarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryOrderServer).QueryRemark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QueryOrder/QueryRemark",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryOrderServer).QueryRemark(ctx, req.(*QueryRemarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryOrder_QueryExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryExperienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryOrderServer).QueryExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QueryOrder/QueryExperience",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryOrderServer).QueryExperience(ctx, req.(*QueryExperienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryOrder_QueryAgentOfOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryOrderServer).QueryAgentOfOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QueryOrder/QueryAgentOfOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryOrderServer).QueryAgentOfOrder(ctx, req.(*QueryAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryOrder_QueryOrderOfAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOOARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryOrderServer).QueryOrderOfAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QueryOrder/QueryOrderOfAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryOrderServer).QueryOrderOfAgent(ctx, req.(*QueryOOARequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QueryOrder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "QueryOrder",
	HandlerType: (*QueryOrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryOrder",
			Handler:    _QueryOrder_QueryOrder_Handler,
		},
		{
			MethodName: "QueryPTOfOrder",
			Handler:    _QueryOrder_QueryPTOfOrder_Handler,
		},
		{
			MethodName: "QueryRemark",
			Handler:    _QueryOrder_QueryRemark_Handler,
		},
		{
			MethodName: "QueryExperience",
			Handler:    _QueryOrder_QueryExperience_Handler,
		},
		{
			MethodName: "QueryAgentOfOrder",
			Handler:    _QueryOrder_QueryAgentOfOrder_Handler,
		},
		{
			MethodName: "QueryOrderOfAgent",
			Handler:    _QueryOrder_QueryOrderOfAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "query.proto",
}
