/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.go.micro.srv.GetOrder.Response');
goog.provide('proto.go.micro.srv.GetOrder.Response.order');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.go.micro.srv.GetOrder.Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.go.micro.srv.GetOrder.Response.repeatedFields_, null);
};
goog.inherits(proto.go.micro.srv.GetOrder.Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.go.micro.srv.GetOrder.Response.displayName = 'proto.go.micro.srv.GetOrder.Response';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.go.micro.srv.GetOrder.Response.order = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.go.micro.srv.GetOrder.Response.order, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.go.micro.srv.GetOrder.Response.order.displayName = 'proto.go.micro.srv.GetOrder.Response.order';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.go.micro.srv.GetOrder.Response.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.go.micro.srv.GetOrder.Response.prototype.toObject = function(opt_includeInstance) {
  return proto.go.micro.srv.GetOrder.Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.go.micro.srv.GetOrder.Response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.go.micro.srv.GetOrder.Response.toObject = function(includeInstance, msg) {
  var f, obj = {
    errno: jspb.Message.getFieldWithDefault(msg, 1, ""),
    errmsg: jspb.Message.getFieldWithDefault(msg, 2, ""),
    dataList: jspb.Message.toObjectList(msg.getDataList(),
    proto.go.micro.srv.GetOrder.Response.order.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.go.micro.srv.GetOrder.Response}
 */
proto.go.micro.srv.GetOrder.Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.go.micro.srv.GetOrder.Response;
  return proto.go.micro.srv.GetOrder.Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.go.micro.srv.GetOrder.Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.go.micro.srv.GetOrder.Response}
 */
proto.go.micro.srv.GetOrder.Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrno(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrmsg(value);
      break;
    case 3:
      var value = new proto.go.micro.srv.GetOrder.Response.order;
      reader.readMessage(value,proto.go.micro.srv.GetOrder.Response.order.deserializeBinaryFromReader);
      msg.addData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.go.micro.srv.GetOrder.Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.go.micro.srv.GetOrder.Response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.go.micro.srv.GetOrder.Response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.go.micro.srv.GetOrder.Response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getErrno();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getErrmsg();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDataList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.go.micro.srv.GetOrder.Response.order.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.go.micro.srv.GetOrder.Response.order.prototype.toObject = function(opt_includeInstance) {
  return proto.go.micro.srv.GetOrder.Response.order.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.go.micro.srv.GetOrder.Response.order} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.go.micro.srv.GetOrder.Response.order.toObject = function(includeInstance, msg) {
  var f, obj = {
    orderid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    orderuser: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.go.micro.srv.GetOrder.Response.order}
 */
proto.go.micro.srv.GetOrder.Response.order.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.go.micro.srv.GetOrder.Response.order;
  return proto.go.micro.srv.GetOrder.Response.order.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.go.micro.srv.GetOrder.Response.order} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.go.micro.srv.GetOrder.Response.order}
 */
proto.go.micro.srv.GetOrder.Response.order.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOrderid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderuser(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.go.micro.srv.GetOrder.Response.order.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.go.micro.srv.GetOrder.Response.order.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.go.micro.srv.GetOrder.Response.order} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.go.micro.srv.GetOrder.Response.order.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrderid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getOrderuser();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int64 orderid = 1;
 * @return {number}
 */
proto.go.micro.srv.GetOrder.Response.order.prototype.getOrderid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.go.micro.srv.GetOrder.Response.order.prototype.setOrderid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string orderuser = 2;
 * @return {string}
 */
proto.go.micro.srv.GetOrder.Response.order.prototype.getOrderuser = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.go.micro.srv.GetOrder.Response.order.prototype.setOrderuser = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string errno = 1;
 * @return {string}
 */
proto.go.micro.srv.GetOrder.Response.prototype.getErrno = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.go.micro.srv.GetOrder.Response.prototype.setErrno = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string errmsg = 2;
 * @return {string}
 */
proto.go.micro.srv.GetOrder.Response.prototype.getErrmsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.go.micro.srv.GetOrder.Response.prototype.setErrmsg = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated order data = 3;
 * @return {!Array<!proto.go.micro.srv.GetOrder.Response.order>}
 */
proto.go.micro.srv.GetOrder.Response.prototype.getDataList = function() {
  return /** @type{!Array<!proto.go.micro.srv.GetOrder.Response.order>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.go.micro.srv.GetOrder.Response.order, 3));
};


/** @param {!Array<!proto.go.micro.srv.GetOrder.Response.order>} value */
proto.go.micro.srv.GetOrder.Response.prototype.setDataList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.go.micro.srv.GetOrder.Response.order=} opt_value
 * @param {number=} opt_index
 * @return {!proto.go.micro.srv.GetOrder.Response.order}
 */
proto.go.micro.srv.GetOrder.Response.prototype.addData = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.go.micro.srv.GetOrder.Response.order, opt_index);
};


proto.go.micro.srv.GetOrder.Response.prototype.clearDataList = function() {
  this.setDataList([]);
};


