// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	Errno                string           `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string           `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data                 []*ResponseOrder `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetData() []*ResponseOrder {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResponseOrder struct {
	Orderid              int64    `protobuf:"varint,1,opt,name=orderid,proto3" json:"orderid,omitempty"`
	Orderuser            string   `protobuf:"bytes,2,opt,name=orderuser,proto3" json:"orderuser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseOrder) Reset()         { *m = ResponseOrder{} }
func (m *ResponseOrder) String() string { return proto.CompactTextString(m) }
func (*ResponseOrder) ProtoMessage()    {}
func (*ResponseOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1, 0}
}

func (m *ResponseOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseOrder.Unmarshal(m, b)
}
func (m *ResponseOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseOrder.Marshal(b, m, deterministic)
}
func (m *ResponseOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseOrder.Merge(m, src)
}
func (m *ResponseOrder) XXX_Size() int {
	return xxx_messageInfo_ResponseOrder.Size(m)
}
func (m *ResponseOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseOrder proto.InternalMessageInfo

func (m *ResponseOrder) GetOrderid() int64 {
	if m != nil {
		return m.Orderid
	}
	return 0
}

func (m *ResponseOrder) GetOrderuser() string {
	if m != nil {
		return m.Orderuser
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetOrder.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetOrder.Response")
	proto.RegisterType((*ResponseOrder)(nil), "go.micro.srv.GetOrder.Response.order")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x3f, 0x4b, 0xc7, 0x30,
	0x10, 0x86, 0xad, 0xf5, 0xd7, 0x3f, 0xe7, 0x76, 0xa8, 0x84, 0x2a, 0x5a, 0x0a, 0x42, 0xa7, 0x08,
	0x75, 0x72, 0x72, 0x12, 0x27, 0x11, 0x32, 0xb9, 0x56, 0x7b, 0x94, 0x82, 0x6d, 0xea, 0x25, 0x15,
	0x3f, 0x98, 0x1f, 0x50, 0xbc, 0x36, 0xb8, 0x28, 0x4e, 0xb9, 0xe7, 0x85, 0xe4, 0xb9, 0x37, 0x70,
	0x3a, 0xb3, 0xf5, 0xf6, 0x8a, 0x3e, 0xda, 0x71, 0x7e, 0xa5, 0x70, 0x6a, 0x49, 0xf1, 0xb8, 0xb7,
	0x7a, 0x1c, 0x5e, 0xd8, 0x6a, 0xc7, 0xef, 0xfa, 0x9e, 0xfc, 0x23, 0x77, 0xc4, 0x55, 0x0e, 0xa9,
	0xa1, 0xb7, 0x85, 0x9c, 0xaf, 0x3e, 0x23, 0xc8, 0x0c, 0xb9, 0xd9, 0x4e, 0x8e, 0xf0, 0x08, 0x76,
	0xc4, 0x3c, 0x59, 0x15, 0x95, 0x51, 0x9d, 0x9b, 0x15, 0xf0, 0x04, 0x12, 0x62, 0x1e, 0x5d, 0xaf,
	0xf6, 0x25, 0xde, 0x08, 0x6f, 0xe0, 0xa0, 0x6b, 0x7d, 0xab, 0xe2, 0x32, 0xae, 0x0f, 0x9b, 0x4b,
	0xfd, 0xab, 0x4b, 0x87, 0xc7, 0xb5, 0xfd, 0x46, 0x23, 0x57, 0x8a, 0x5b, 0xd8, 0x09, 0xa2, 0x82,
	0x54, 0x86, 0xa1, 0x13, 0x67, 0x6c, 0x02, 0xe2, 0x19, 0xe4, 0x32, 0x2e, 0x8e, 0x78, 0x13, 0xff,
	0x04, 0xcd, 0x13, 0xa4, 0x77, 0x6b, 0x53, 0x7c, 0x80, 0x2c, 0xc8, 0xf0, 0xfc, 0xcf, 0x25, 0xa4,
	0x6d, 0x71, 0xf1, 0xcf, 0x92, 0xd5, 0xde, 0x73, 0x22, 0x3f, 0x77, 0xfd, 0x15, 0x00, 0x00, 0xff,
	0xff, 0x9d, 0xb9, 0x60, 0xff, 0x58, 0x01, 0x00, 0x00,
}
