// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mutationorder.proto

package mutationorder

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HotelCreateOrderRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Job                  string   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	Date                 uint64   `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	StartTime            uint64   `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Duration             uint64   `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Count                uint64   `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	CountMale            uint64   `protobuf:"varint,7,opt,name=count_male,json=countMale,proto3" json:"count_male,omitempty"`
	CountFemale          uint64   `protobuf:"varint,8,opt,name=count_female,json=countFemale,proto3" json:"count_female,omitempty"`
	Adviser              uint64   `protobuf:"varint,9,opt,name=adviser,proto3" json:"adviser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HotelCreateOrderRequest) Reset()         { *m = HotelCreateOrderRequest{} }
func (m *HotelCreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*HotelCreateOrderRequest) ProtoMessage()    {}
func (*HotelCreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bb452dc293c04f6, []int{0}
}

func (m *HotelCreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotelCreateOrderRequest.Unmarshal(m, b)
}
func (m *HotelCreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotelCreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *HotelCreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotelCreateOrderRequest.Merge(m, src)
}
func (m *HotelCreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_HotelCreateOrderRequest.Size(m)
}
func (m *HotelCreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HotelCreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HotelCreateOrderRequest proto.InternalMessageInfo

func (m *HotelCreateOrderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HotelCreateOrderRequest) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *HotelCreateOrderRequest) GetDate() uint64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *HotelCreateOrderRequest) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *HotelCreateOrderRequest) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *HotelCreateOrderRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *HotelCreateOrderRequest) GetCountMale() uint64 {
	if m != nil {
		return m.CountMale
	}
	return 0
}

func (m *HotelCreateOrderRequest) GetCountFemale() uint64 {
	if m != nil {
		return m.CountFemale
	}
	return 0
}

func (m *HotelCreateOrderRequest) GetAdviser() uint64 {
	if m != nil {
		return m.Adviser
	}
	return 0
}

type HotelCreateOrderReply struct {
	OrderId              uint64   `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CreateResult         string   `protobuf:"bytes,2,opt,name=create_result,json=createResult,proto3" json:"create_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HotelCreateOrderReply) Reset()         { *m = HotelCreateOrderReply{} }
func (m *HotelCreateOrderReply) String() string { return proto.CompactTextString(m) }
func (*HotelCreateOrderReply) ProtoMessage()    {}
func (*HotelCreateOrderReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bb452dc293c04f6, []int{1}
}

func (m *HotelCreateOrderReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotelCreateOrderReply.Unmarshal(m, b)
}
func (m *HotelCreateOrderReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotelCreateOrderReply.Marshal(b, m, deterministic)
}
func (m *HotelCreateOrderReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotelCreateOrderReply.Merge(m, src)
}
func (m *HotelCreateOrderReply) XXX_Size() int {
	return xxx_messageInfo_HotelCreateOrderReply.Size(m)
}
func (m *HotelCreateOrderReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HotelCreateOrderReply.DiscardUnknown(m)
}

var xxx_messageInfo_HotelCreateOrderReply proto.InternalMessageInfo

func (m *HotelCreateOrderReply) GetOrderId() uint64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *HotelCreateOrderReply) GetCreateResult() string {
	if m != nil {
		return m.CreateResult
	}
	return ""
}

func init() {
	proto.RegisterType((*HotelCreateOrderRequest)(nil), "HotelCreateOrderRequest")
	proto.RegisterType((*HotelCreateOrderReply)(nil), "HotelCreateOrderReply")
}

func init() { proto.RegisterFile("mutationorder.proto", fileDescriptor_4bb452dc293c04f6) }

var fileDescriptor_4bb452dc293c04f6 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x4d, 0x9b, 0x36, 0xc9, 0x58, 0xb1, 0x8c, 0xff, 0xd6, 0x82, 0x50, 0xe3, 0xa5, 0xa7,
	0x1c, 0xf4, 0x23, 0x08, 0x45, 0x0f, 0x41, 0x08, 0x82, 0x78, 0x0a, 0xdb, 0xee, 0x28, 0x91, 0x24,
	0x5b, 0x37, 0x13, 0xc1, 0x9b, 0x1f, 0x5d, 0x32, 0xa9, 0x1e, 0xfc, 0x73, 0x7b, 0xef, 0xf7, 0x1e,
	0xbb, 0xcb, 0x5b, 0x38, 0xa8, 0x5a, 0xd6, 0x5c, 0xd8, 0xda, 0x3a, 0x43, 0x2e, 0xd9, 0x38, 0xcb,
	0x36, 0xfe, 0x18, 0xc0, 0xc9, 0x8d, 0x65, 0x2a, 0xaf, 0x1d, 0x69, 0xa6, 0xbb, 0x2e, 0xca, 0xe8,
	0xb5, 0xa5, 0x86, 0x11, 0xc1, 0xaf, 0x75, 0x45, 0xca, 0x9b, 0x7b, 0x8b, 0x28, 0x13, 0x8d, 0x53,
	0x18, 0xbe, 0xd8, 0x95, 0x1a, 0x08, 0xea, 0x64, 0xd7, 0x32, 0x9a, 0x49, 0x0d, 0xe7, 0xde, 0xc2,
	0xcf, 0x44, 0xe3, 0x19, 0x40, 0xc3, 0xda, 0x71, 0xce, 0x45, 0x45, 0xca, 0x97, 0x24, 0x12, 0x72,
	0x5f, 0x54, 0x84, 0x33, 0x08, 0x4d, 0xeb, 0xe4, 0x2d, 0x6a, 0x24, 0xe1, 0xb7, 0xc7, 0x43, 0x18,
	0xad, 0x6d, 0x5b, 0xb3, 0x1a, 0x4b, 0xd0, 0x9b, 0xee, 0x40, 0x11, 0x79, 0xa5, 0x4b, 0x52, 0x41,
	0x7f, 0xa0, 0x90, 0x54, 0x97, 0x84, 0xe7, 0x30, 0xe9, 0xe3, 0x27, 0x92, 0x42, 0x28, 0x85, 0x5d,
	0x61, 0x4b, 0x41, 0xa8, 0x20, 0xd0, 0xe6, 0xad, 0x68, 0xc8, 0xa9, 0x48, 0xd2, 0x2f, 0x1b, 0x3f,
	0xc0, 0xd1, 0xef, 0x05, 0x36, 0xe5, 0x3b, 0x9e, 0x42, 0x28, 0x53, 0xe5, 0x85, 0x91, 0x0d, 0xfc,
	0x2c, 0x10, 0x7f, 0x6b, 0xf0, 0x02, 0xf6, 0xd6, 0x52, 0xcf, 0x1d, 0x35, 0x6d, 0xc9, 0xdb, 0x41,
	0x26, 0x3d, 0xcc, 0x84, 0x5d, 0x3e, 0xc2, 0x7e, 0xba, 0x9d, 0x3c, 0xd5, 0xb5, 0x7e, 0x26, 0x87,
	0x4b, 0x98, 0xfe, 0xbc, 0x0b, 0x55, 0xf2, 0xcf, 0x07, 0xcc, 0x8e, 0x93, 0x3f, 0x1f, 0x16, 0xef,
	0xac, 0xc6, 0xf2, 0x7b, 0x57, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xa1, 0x09, 0x08, 0xd4,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MutationManagerClient is the client API for MutationManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MutationManagerClient interface {
	//hotel create order
	HotelCreateOrder(ctx context.Context, in *HotelCreateOrderRequest, opts ...grpc.CallOption) (*HotelCreateOrderReply, error)
}

type mutationManagerClient struct {
	cc *grpc.ClientConn
}

func NewMutationManagerClient(cc *grpc.ClientConn) MutationManagerClient {
	return &mutationManagerClient{cc}
}

func (c *mutationManagerClient) HotelCreateOrder(ctx context.Context, in *HotelCreateOrderRequest, opts ...grpc.CallOption) (*HotelCreateOrderReply, error) {
	out := new(HotelCreateOrderReply)
	err := c.cc.Invoke(ctx, "/MutationManager/HotelCreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MutationManagerServer is the server API for MutationManager service.
type MutationManagerServer interface {
	//hotel create order
	HotelCreateOrder(context.Context, *HotelCreateOrderRequest) (*HotelCreateOrderReply, error)
}

// UnimplementedMutationManagerServer can be embedded to have forward compatible implementations.
type UnimplementedMutationManagerServer struct {
}

func (*UnimplementedMutationManagerServer) HotelCreateOrder(ctx context.Context, req *HotelCreateOrderRequest) (*HotelCreateOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HotelCreateOrder not implemented")
}

func RegisterMutationManagerServer(s *grpc.Server, srv MutationManagerServer) {
	s.RegisterService(&_MutationManager_serviceDesc, srv)
}

func _MutationManager_HotelCreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotelCreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutationManagerServer).HotelCreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MutationManager/HotelCreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutationManagerServer).HotelCreateOrder(ctx, req.(*HotelCreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MutationManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MutationManager",
	HandlerType: (*MutationManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HotelCreateOrder",
			Handler:    _MutationManager_HotelCreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mutationorder.proto",
}
