// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderOperation.proto

package orderOperation

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HotelCreateOrderRequest struct {
	HotelId              string   `protobuf:"bytes,1,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	Job                  string   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	Date                 int32    `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Duration             int32    `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Count                int32    `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	CountMale            int32    `protobuf:"varint,6,opt,name=count_male,json=countMale,proto3" json:"count_male,omitempty"`
	CountFemale          int32    `protobuf:"varint,7,opt,name=count_female,json=countFemale,proto3" json:"count_female,omitempty"`
	AdviserId            string   `protobuf:"bytes,8,opt,name=adviser_id,json=adviserId,proto3" json:"adviser_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HotelCreateOrderRequest) Reset()         { *m = HotelCreateOrderRequest{} }
func (m *HotelCreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*HotelCreateOrderRequest) ProtoMessage()    {}
func (*HotelCreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf54367236c2b9a3, []int{0}
}

func (m *HotelCreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotelCreateOrderRequest.Unmarshal(m, b)
}
func (m *HotelCreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotelCreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *HotelCreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotelCreateOrderRequest.Merge(m, src)
}
func (m *HotelCreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_HotelCreateOrderRequest.Size(m)
}
func (m *HotelCreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HotelCreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HotelCreateOrderRequest proto.InternalMessageInfo

func (m *HotelCreateOrderRequest) GetHotelId() string {
	if m != nil {
		return m.HotelId
	}
	return ""
}

func (m *HotelCreateOrderRequest) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *HotelCreateOrderRequest) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *HotelCreateOrderRequest) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *HotelCreateOrderRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *HotelCreateOrderRequest) GetCountMale() int32 {
	if m != nil {
		return m.CountMale
	}
	return 0
}

func (m *HotelCreateOrderRequest) GetCountFemale() int32 {
	if m != nil {
		return m.CountFemale
	}
	return 0
}

func (m *HotelCreateOrderRequest) GetAdviserId() string {
	if m != nil {
		return m.AdviserId
	}
	return ""
}

type HotelCreateOrderReply struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CreateResult         string   `protobuf:"bytes,2,opt,name=create_result,json=createResult,proto3" json:"create_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HotelCreateOrderReply) Reset()         { *m = HotelCreateOrderReply{} }
func (m *HotelCreateOrderReply) String() string { return proto.CompactTextString(m) }
func (*HotelCreateOrderReply) ProtoMessage()    {}
func (*HotelCreateOrderReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf54367236c2b9a3, []int{1}
}

func (m *HotelCreateOrderReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotelCreateOrderReply.Unmarshal(m, b)
}
func (m *HotelCreateOrderReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotelCreateOrderReply.Marshal(b, m, deterministic)
}
func (m *HotelCreateOrderReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotelCreateOrderReply.Merge(m, src)
}
func (m *HotelCreateOrderReply) XXX_Size() int {
	return xxx_messageInfo_HotelCreateOrderReply.Size(m)
}
func (m *HotelCreateOrderReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HotelCreateOrderReply.DiscardUnknown(m)
}

var xxx_messageInfo_HotelCreateOrderReply proto.InternalMessageInfo

func (m *HotelCreateOrderReply) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *HotelCreateOrderReply) GetCreateResult() string {
	if m != nil {
		return m.CreateResult
	}
	return ""
}

type QueryOrderRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOrderRequest) Reset()         { *m = QueryOrderRequest{} }
func (m *QueryOrderRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOrderRequest) ProtoMessage()    {}
func (*QueryOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf54367236c2b9a3, []int{2}
}

func (m *QueryOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrderRequest.Unmarshal(m, b)
}
func (m *QueryOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrderRequest.Marshal(b, m, deterministic)
}
func (m *QueryOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrderRequest.Merge(m, src)
}
func (m *QueryOrderRequest) XXX_Size() int {
	return xxx_messageInfo_QueryOrderRequest.Size(m)
}
func (m *QueryOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrderRequest proto.InternalMessageInfo

func (m *QueryOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type QueryOrderReply struct {
	HotelId              string   `protobuf:"bytes,1,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	Job                  string   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	Date                 int32    `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Duration             int32    `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Count                int32    `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	CountMale            int32    `protobuf:"varint,6,opt,name=count_male,json=countMale,proto3" json:"count_male,omitempty"`
	CountFemale          int32    `protobuf:"varint,7,opt,name=count_female,json=countFemale,proto3" json:"count_female,omitempty"`
	AdviserId            string   `protobuf:"bytes,8,opt,name=adviser_id,json=adviserId,proto3" json:"adviser_id,omitempty"`
	Mode                 int32    `protobuf:"varint,9,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOrderReply) Reset()         { *m = QueryOrderReply{} }
func (m *QueryOrderReply) String() string { return proto.CompactTextString(m) }
func (*QueryOrderReply) ProtoMessage()    {}
func (*QueryOrderReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf54367236c2b9a3, []int{3}
}

func (m *QueryOrderReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrderReply.Unmarshal(m, b)
}
func (m *QueryOrderReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrderReply.Marshal(b, m, deterministic)
}
func (m *QueryOrderReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrderReply.Merge(m, src)
}
func (m *QueryOrderReply) XXX_Size() int {
	return xxx_messageInfo_QueryOrderReply.Size(m)
}
func (m *QueryOrderReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrderReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrderReply proto.InternalMessageInfo

func (m *QueryOrderReply) GetHotelId() string {
	if m != nil {
		return m.HotelId
	}
	return ""
}

func (m *QueryOrderReply) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *QueryOrderReply) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *QueryOrderReply) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *QueryOrderReply) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryOrderReply) GetCountMale() int32 {
	if m != nil {
		return m.CountMale
	}
	return 0
}

func (m *QueryOrderReply) GetCountFemale() int32 {
	if m != nil {
		return m.CountFemale
	}
	return 0
}

func (m *QueryOrderReply) GetAdviserId() string {
	if m != nil {
		return m.AdviserId
	}
	return ""
}

func (m *QueryOrderReply) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func init() {
	proto.RegisterType((*HotelCreateOrderRequest)(nil), "HotelCreateOrderRequest")
	proto.RegisterType((*HotelCreateOrderReply)(nil), "HotelCreateOrderReply")
	proto.RegisterType((*QueryOrderRequest)(nil), "QueryOrderRequest")
	proto.RegisterType((*QueryOrderReply)(nil), "QueryOrderReply")
}

func init() { proto.RegisterFile("orderOperation.proto", fileDescriptor_bf54367236c2b9a3) }

var fileDescriptor_bf54367236c2b9a3 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x93, 0xcf, 0x4e, 0x3a, 0x31,
	0x10, 0xc7, 0xd9, 0x1f, 0x7f, 0x77, 0x7e, 0xa8, 0x38, 0x41, 0xad, 0x24, 0x26, 0x58, 0x2f, 0x9c,
	0x7a, 0x50, 0xdf, 0xc0, 0x84, 0xc8, 0xc1, 0x10, 0xf7, 0xe2, 0x91, 0x14, 0x3a, 0x46, 0xcc, 0x42,
	0xb1, 0x74, 0x4d, 0x78, 0x09, 0xdf, 0xd4, 0x07, 0xf0, 0x66, 0x3a, 0x4b, 0x14, 0x17, 0x79, 0x01,
	0x6f, 0x33, 0x9f, 0x99, 0xed, 0x7e, 0xe7, 0x3b, 0x2d, 0xb4, 0xad, 0x33, 0xe4, 0x86, 0x0b, 0x72,
	0xda, 0x4f, 0xed, 0x5c, 0x2d, 0x9c, 0xf5, 0x56, 0xbe, 0x47, 0x70, 0x72, 0x6b, 0x3d, 0xa5, 0x37,
	0x8e, 0xb4, 0xa7, 0x61, 0xe8, 0x49, 0xe8, 0x25, 0xa3, 0xa5, 0xc7, 0x53, 0x68, 0x3c, 0x85, 0xd2,
	0x68, 0x6a, 0x44, 0xd4, 0x8d, 0x7a, 0x71, 0x52, 0xe7, 0x7c, 0x60, 0xb0, 0x05, 0xe5, 0x67, 0x3b,
	0x16, 0xff, 0x98, 0x86, 0x10, 0x11, 0x2a, 0x46, 0x7b, 0x12, 0xe5, 0x6e, 0xd4, 0xab, 0x26, 0x1c,
	0x63, 0x07, 0x1a, 0x26, 0xcb, 0x7f, 0x27, 0x2a, 0xcc, 0xbf, 0x72, 0x6c, 0x43, 0x75, 0x62, 0xb3,
	0xb9, 0x17, 0x55, 0x2e, 0xe4, 0x09, 0x9e, 0x01, 0x70, 0x30, 0x9a, 0xe9, 0x94, 0x44, 0x8d, 0x4b,
	0x31, 0x93, 0x3b, 0x9d, 0x12, 0x9e, 0x43, 0x33, 0x2f, 0x3f, 0x12, 0x37, 0xd4, 0xb9, 0xe1, 0x3f,
	0xb3, 0x3e, 0xa3, 0x70, 0x82, 0x36, 0xaf, 0xd3, 0x25, 0xb9, 0x20, 0xbb, 0xc1, 0x02, 0xe3, 0x35,
	0x19, 0x18, 0xf9, 0x00, 0x47, 0xdb, 0xe3, 0x2e, 0xd2, 0x55, 0x18, 0x96, 0x0d, 0xda, 0x18, 0x96,
	0xf3, 0x81, 0xc1, 0x0b, 0xd8, 0x9b, 0x70, 0xfb, 0xc8, 0xd1, 0x32, 0x4b, 0xfd, 0x7a, 0xec, 0x66,
	0x0e, 0x13, 0x66, 0x52, 0xc1, 0xe1, 0x7d, 0x46, 0x6e, 0x55, 0x74, 0x70, 0xc7, 0xa1, 0xf2, 0x23,
	0x82, 0x83, 0xcd, 0x0f, 0xd6, 0x1a, 0xfe, 0x9a, 0xe1, 0x41, 0xe6, 0xcc, 0x1a, 0x12, 0x71, 0x2e,
	0x33, 0xc4, 0x97, 0x6f, 0x11, 0xec, 0x0f, 0x7f, 0xdc, 0x46, 0xec, 0x43, 0xab, 0xb8, 0x17, 0x14,
	0x6a, 0xc7, 0xcd, 0xec, 0x1c, 0xab, 0x5f, 0x97, 0x28, 0x4b, 0x78, 0x0d, 0xf0, 0xed, 0x2a, 0xa2,
	0xda, 0xda, 0x49, 0xa7, 0xa5, 0x0a, 0xb6, 0xcb, 0xd2, 0xb8, 0xc6, 0x8f, 0xe1, 0xea, 0x33, 0x00,
	0x00, 0xff, 0xff, 0xd1, 0xf0, 0xc9, 0x6a, 0x24, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderOperationClient is the client API for OrderOperation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderOperationClient interface {
	//hotel create order
	HotelCreateOrder(ctx context.Context, in *HotelCreateOrderRequest, opts ...grpc.CallOption) (*HotelCreateOrderReply, error)
	//query order
	QueryOrder(ctx context.Context, in *QueryOrderRequest, opts ...grpc.CallOption) (*QueryOrderReply, error)
}

type orderOperationClient struct {
	cc *grpc.ClientConn
}

func NewOrderOperationClient(cc *grpc.ClientConn) OrderOperationClient {
	return &orderOperationClient{cc}
}

func (c *orderOperationClient) HotelCreateOrder(ctx context.Context, in *HotelCreateOrderRequest, opts ...grpc.CallOption) (*HotelCreateOrderReply, error) {
	out := new(HotelCreateOrderReply)
	err := c.cc.Invoke(ctx, "/OrderOperation/HotelCreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderOperationClient) QueryOrder(ctx context.Context, in *QueryOrderRequest, opts ...grpc.CallOption) (*QueryOrderReply, error) {
	out := new(QueryOrderReply)
	err := c.cc.Invoke(ctx, "/OrderOperation/QueryOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderOperationServer is the server API for OrderOperation service.
type OrderOperationServer interface {
	//hotel create order
	HotelCreateOrder(context.Context, *HotelCreateOrderRequest) (*HotelCreateOrderReply, error)
	//query order
	QueryOrder(context.Context, *QueryOrderRequest) (*QueryOrderReply, error)
}

// UnimplementedOrderOperationServer can be embedded to have forward compatible implementations.
type UnimplementedOrderOperationServer struct {
}

func (*UnimplementedOrderOperationServer) HotelCreateOrder(ctx context.Context, req *HotelCreateOrderRequest) (*HotelCreateOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HotelCreateOrder not implemented")
}
func (*UnimplementedOrderOperationServer) QueryOrder(ctx context.Context, req *QueryOrderRequest) (*QueryOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOrder not implemented")
}

func RegisterOrderOperationServer(s *grpc.Server, srv OrderOperationServer) {
	s.RegisterService(&_OrderOperation_serviceDesc, srv)
}

func _OrderOperation_HotelCreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotelCreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderOperationServer).HotelCreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OrderOperation/HotelCreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderOperationServer).HotelCreateOrder(ctx, req.(*HotelCreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderOperation_QueryOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderOperationServer).QueryOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OrderOperation/QueryOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderOperationServer).QueryOrder(ctx, req.(*QueryOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderOperation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "OrderOperation",
	HandlerType: (*OrderOperationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HotelCreateOrder",
			Handler:    _OrderOperation_HotelCreateOrder_Handler,
		},
		{
			MethodName: "QueryOrder",
			Handler:    _OrderOperation_QueryOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orderOperation.proto",
}
